apiVersion: v1
kind: Service
metadata:
  labels:
    app: demoapp
  name: demosvc
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: demoapp
  type: NodePort
status:
  loadBalancer: {}
